// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuSGdhOv9X8V3RUlKdiMg1TlHYgKQ068k',
    appId: '1:48920761156:web:c003366fc58a0cca113d11',
    messagingSenderId: '48920761156',
    projectId: 'free-games-api',
    authDomain: 'free-games-api.firebaseapp.com',
    storageBucket: 'free-games-api.appspot.com',
    measurementId: 'G-DM2JLXENRB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ914g3_9EPvZKLCsuPGrO9giwvctLGIQ',
    appId: '1:48920761156:android:8e0494c066c431d7113d11',
    messagingSenderId: '48920761156',
    projectId: 'free-games-api',
    storageBucket: 'free-games-api.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0wqolHQYCNOXNdWAk7xBsxo1_zyTb680',
    appId: '1:48920761156:ios:4d09e9b8cecd7130113d11',
    messagingSenderId: '48920761156',
    projectId: 'free-games-api',
    storageBucket: 'free-games-api.appspot.com',
    iosClientId: '48920761156-9lppv8dmu8vns1tb2j6ogjbp4rnb5ljh.apps.googleusercontent.com',
    iosBundleId: 'com.codekoalas.freegamesexample',
  );
}
