name: Dart CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - run: flutter packages get
    - run: flutter test --coverage
    - name: Upload coverage to Codecov  
      uses: codecov/codecov-action@v2
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        directory: coverage
        file: lcov.info
        verbose: true